### PR TITLE
Fix positioning scroll persistance

### PR DESCRIPTION
**Pull request by flexyford**
Add integration testing (previously unit tests)

These tests exercise standard functionality and I have added tests and fixes for use-cases which I found were broken. 

I was unable to update the list when using jquery scroll events, however, I was able to mock scrolling by setting the positionIndex. **Need to open an issue for scrolling in the integration tests!**

Added tests and fixed the following:

> Fix Test: Setting a position index past the maximum top index should place the last visible item flush with the bottom of the visibleContent. Previously, it set the maximum top visible item was set flush with the top of the visible content, which could leave the final item cut-off depending on the `height` of the `virtual-each` and the `itemHeight`

My team and I are implementing [ember-impagination - README Pending] (https://github.com/thefrontside/ember-impagination) which is an infinite-scroll component. This implementation will continually update the immutable `items` array, which will fire the `didReceiveAttrs` hook. Therefore, we need to persists the positionIndex if the items are updated

 > Fix Test: persist position index if `items` array is updated

### CODE REVIEW

**Comment by jasonmit** [comment]
Persisting the index should be optional and driven by an attribute.  Otherwise, all in favor.

I will review the PR when I get back to my computer.

**Comment by jasonmit** [comment]
> I was unable to update the list when using jquery scroll events, however, I was able to mock scrolling by setting the positionIndex

I figured that was going to be an issue.

> This implementation will continually update the immutable items array, which will fire the didReceiveAttrs hook. Therefore, we need to persists the positionIndex if the items are updated

Disregard my previous comment.  I'm all in favor of this.

**Comment by jasonmit** [comment]
Also, you've been added as an npm owner along with Robert

**Comment by flexyford** [comment]
Thanks jasonmit! 

When we want to persist the positionIndex internally, the position index should remain 'undefined'. Therefore, if we want to reset the items array to the beginning of the array, the positionIndex should be set to zero for that instance! Should we maybe consider adding a `reset` attr instead?

I will add persisting functionality documentation to the README

**Comment by jasonmit** [comment]
@flexyford I don't really like the idea of a attribute to drive reset behavior.

Instead, we should be able to hook into the didReceiveAttrs to know what the user switched the position index back to 0.  In order for this to all work, we may need to implement position index as internal state and action for `positionIndexChanged`.  This would make this flow subscribe to DDAU.

**Comment by paynen** [comment]
This also fixes an issue where `_visibleItemCount` is greater than the number of items to display which resulted in the scroll position being negative and so screwed up the display of the list.  I've got a project that needs this fix, so would it be possible to release a version with this fix?

**Comment by flexyford** [comment]
Just released version 0.0.12 which contains this fix. Thanks @paynen

**Comment by paynen** [comment]
Thanks  :+1:

**Pull request merged**
